name: Test Aiohttp App
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Test Application
        run: pytest
      - name: Lint Application
        run: |
          pip install pylint
          pylint --recursive=y --exit-zero app
      - name: Build Application
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build
      - name: Deploy
        run: echo Deploying ...
