name: Print Pull Request Context
on:
  workflow_dispatch:  #Все триггеры см на github actions workflows triggers
  pull_request:
    types: [opened, edited, reopened]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Context
        run: echo "${{ toJSON(github.event) }}"
