name: Test Aiohttp App
on:
  push:
    branches:
      - main
#    paths-ignore:
#      - '.github/workflows/*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Test Application
        run: pytest
  lint:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get the repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint Application
        run: |
          pip install pylint
          pylint --recursive=y --exit-zero app
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get the repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build Application
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build
      - name: Deploy
        run: echo Deploying ...
